### Double & to keep formatting while getting rid of linebreaks

### eko
POST localhost:5000/alphabot
Content-Type: application/x-www-form-urlencoded

token=cNYvAHS2BthPjONp9ro64qNw&
&team_id=T02V5AV3Q&
&team_domain=alphadevab&
&enterprise_id=E0001&
&enterprise_name=Globular%20Construct%20Inc&
&channel_id=CEYLL3PC1&
&channel_name=test&
&user_id=U09JBPRRQ&
&user_name=leon&
&command=/alphabot&
&text=eko%20hej%20hej%20hej&
&response_url=https://hooks.slack.com/commands/T02V5AV3Q/508773119153/JwX0p1NbCrbiIfjSkp2mwoK1&
&trigger_id=509375562626.2991369126.d0adbb47a0be7237196f4a35c6de30d1

### icebreak
POST localhost:5000/alphabot
Content-Type: application/x-www-form-urlencoded

token=cNYvAHS2BthPjONp9ro64qNw&
&team_id=T02V5AV3Q&
&team_domain=alphadevab&
&enterprise_id=E0001&
&enterprise_name=Globular%20Construct%20Inc&
&channel_id=CEYLL3PC1&
&channel_name=test&
&user_id=U09JBPRRQ&
&user_name=leon&
&command=/alphabot&
&text=icebreak%203&
&response_url=https://hooks.slack.com/commands/T02V5AV3Q/508773119153/JwX0p1NbCrbiIfjSkp2mwoK1&
&trigger_id=509375562626.2991369126.d0adbb47a0be7237196f4a35c6de30d1


### celebrate
POST localhost:5000/alphabot
Content-Type: application/x-www-form-urlencoded

token=cNYvAHS2BthPjONp9ro64qNw&
&team_id=T02V5AV3Q&
&team_domain=alphadevab&
&enterprise_id=E0001&
&enterprise_name=Globular%20Construct%20Inc&
&channel_id=CEYLL3PC1&
&channel_name=test&
&user_id=U09JBPRRQ&
&user_name=leon&
&command=/alphabot&
&text=celebrate&
&response_url=https://hooks.slack.com/commands/T02V5AV3Q/508773119153/JwX0p1NbCrbiIfjSkp2mwoK1&
&trigger_id=509375562626.2991369126.d0adbb47a0be7237196f4a35c6de30d1

### help
POST localhost:5000/alphabot
Content-Type: application/x-www-form-urlencoded

token=cNYvAHS2BthPjONp9ro64qNw&
&team_id=T02V5AV3Q&
&team_domain=alphadevab&
&enterprise_id=E0001&
&enterprise_name=Globular%20Construct%20Inc&
&channel_id=CEYLL3PC1&
&channel_name=test&
&user_id=U09JBPRRQ&
&user_name=leon&
&command=/alphabot&
&text=&
&response_url=https://hooks.slack.com/commands/T02V5AV3Q/508773119153/JwX0p1NbCrbiIfjSkp2mwoK1&
&trigger_id=509375562626.2991369126.d0adbb47a0be7237196f4a35c6de30d1

###
